eShopSolution/eShopSolution.AdminApp/Controllers/Components/PagerViewComponent.cs
using eShopSolution.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eShopSolution.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

eShopSolution/eShopSolution.AdminApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using eShopSolution.ApiIntegration;
using eShopSolution.ViewModels.Common;
using eShopSolution.ViewModels.System.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;

namespace eShopSolution.AdminApp.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;
        private readonly IRoleApiClient _roleApiClient;

        public UserController(IUserApiClient userApiClient,
            IRoleApiClient roleApiClient,
            IConfiguration configuration)
        {
            _userApiClient = userApiClient;
            _configuration = configuration;
            _roleApiClient = roleApiClient;
        }

        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            var request = new GetUserPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _userApiClient.GetUsersPagings(request);
            ViewBag.Keyword = keyword;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            return View(result.ResultObj);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RegisterRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.RegisterUser(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Thêm mới người dùng thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            if (result.IsSuccessed)
            {
                var user = result.ResultObj;
                var updateRequest = new UserUpdateRequest()
                {
                    Dob = user.Dob,
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    PhoneNumber = user.PhoneNumber,
                    Id = id
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.UpdateUser(request.Id, request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật người dùng thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Token");
            return RedirectToAction("Index", "Login");
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            return View(new UserDeleteRequest()
            {
                Id = id
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UserDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.Delete(request.Id);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Xóa người dùng thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> RoleAssign(Guid id)
        {
            var roleAssignRequest = await GetRoleAssignRequest(id);
            return View(roleAssignRequest);
        }

        [HttpPost]
        public async Task<IActionResult> RoleAssign(RoleAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.RoleAssign(request.Id, request);

            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật quyền thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            var roleAssignRequest = await GetRoleAssignRequest(request.Id);

            return View(roleAssignRequest);
        }

        private async Task<RoleAssignRequest> GetRoleAssignRequest(Guid id)
        {
            var userObj = await _userApiClient.GetById(id);
            var roleObj = await _roleApiClient.GetAll();
            var roleAssignRequest = new RoleAssignRequest();
            foreach (var role in roleObj.ResultObj)
            {
                roleAssignRequest.Roles.Add(new SelectItem()
                {
                    Id = role.Id.ToString(),
                    Name = role.Name,
                    Selected = userObj.ResultObj.Roles.Contains(role.Name)
                });
            }
            return roleAssignRequest;
        }
    }
}

eShopSolution/eShopSolution.AdminApp/Views/User/Create.cshtml
@model eShopSolution.ViewModels.System.Users.RegisterRequest

@{
    ViewData["Title"] = "Tạo mới người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Tạo mới người dùng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Tạo mới người dùng</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Dob" class="control-label"></label>
                        <input asp-for="Dob" class="form-control" />
                        <span asp-validation-for="Dob" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserName" class="control-label"></label>
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword" class="control-label"></label>
                        <input asp-for="ConfirmPassword" class="form-control" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Lưu lại" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eShopSolution/eShopSolution.AdminApp/Views/User/Delete.cshtml
@model eShopSolution.ViewModels.System.Users.UserDeleteRequest

@{
    ViewData["Title"] = "Xóa người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Xóa người dùng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Xóa user</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                </dl>

                <form asp-action="Delete">
                    <input asp-for="Id" type="hidden" />
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

eShopSolution/eShopSolution.AdminApp/Views/User/Details.cshtml
@model eShopSolution.ViewModels.System.Users.UserVm

@{
    ViewData["Title"] = "Chi tiết";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Chi tiết</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Chi tiết</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.UserName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.UserName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Dob)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Dob)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>

eShopSolution/eShopSolution.AdminApp/Views/User/Edit.cshtml
@model eShopSolution.ViewModels.System.Users.UserUpdateRequest

@{
    ViewData["Title"] = "Cập nhật người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Cập nhật người dùng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Cập nhật người dùng</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</a>
        </div>

        <div class="card-body">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Dob" class="control-label"></label>
                        <input asp-for="Dob" class="form-control" />
                        <span asp-validation-for="Dob" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Lưu lại" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

eShopSolution/eShopSolution.AdminApp/Views/User/Index.cshtml
@using eShopSolution.ViewModels.Common;
@model PagedResult<eShopSolution.ViewModels.System.Users.UserVm>

@{
    ViewData["Title"] = "Danh sách người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
    </script>
}
<div class="container-fluid">
    <h1 class="mt-4">Danh sách người dùng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách người dùng</li>
    </ol>
    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <a class="btn btn-success" asp-action="Create" asp-controller="User">Tạo mới</a>
                </div>
                <div class="col-md-6 col-xs-12">
                    <form asp-action="Index" method="get">
                        <div class="row">
                            <div class="col-md-9">
                                <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" />
                            </div>
                            <div class="cold-md-3">
                                <button type="submit" class="btn btn-primary">Tìm</button>
                                <button type="button" onclick="window.location.href='/User/Index'" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                Tên
                            </th>
                            <th>
                                Họ
                            </th>
                            <th>
                                Số điện thoại
                            </th>
                            <th>
                                Tài khoản
                            </th>
                            <th>
                                Email
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Xem", "Details", new { id = item.Id }) |
                                    @Html.ActionLink("Xóa", "Delete", new { id = item.Id }) |
                                    @Html.ActionLink("Gán quyền", "RoleAssign", new { id = item.Id })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>

eShopSolution/eShopSolution.AdminApp/Views/User/RoleAssign.cshtml
@model eShopSolution.ViewModels.System.Users.RoleAssignRequest

@{
    ViewData["Title"] = "Gán quyền";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Gán quyền</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Gán quyền</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</a>
        </div>

        <div class="card-body">
            <form asp-action="RoleAssign">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                @for (var i = 0; i < Model.Roles.Count; i++)
                {
                    <div class="form-group">
                        <label>
                            @Model.Roles[i].Name
                            <input type="checkbox" asp-for="Roles[i].Selected" />
                            <input type="hidden" asp-for="Roles[i].Id" />
                            <input type="hidden" asp-for="Roles[i].Name" />
                        </label>
                    </div>
                }
                <div class="form-group">
                    <input type="submit" value="Lưu lại" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>